apps/cart/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.cart import views
from django.conf import settings

urlpatterns = [
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

apps/catalog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.catalog import views
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<category_slug>[-\w]+)/$',views.product_grid,name='product_grid'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
    url(r'^uploads/(?P<path>.*)$','django.views.static.serve',{"document_root":settings.MEDIA_ROOT,}),
]

shopsys/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/',include('apps.cart.urls',namespace='cart')),
    url(r'^',include('apps.catalog.urls',namespace='shopsys')),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.shortcuts import render
import os
from django.conf import settings

# Create your models here.

class Logos(models.Model):
	"""
	公司logo
	"""
	title = models.CharField("公司名称",max_length=200)
	image_url = models.ImageField("图片路径",upload_to="logo/%Y/%m/%d",blank=True)
	description = models.CharField('描述',max_length=200)
	play = models.BooleanField("是否显示",default=False)

	class Meta:
		verbose_name = '公司logo'
		verbose_name_plural = verbose_name
		ordering = ['id']

	def __str__(self):
		return self.title


class Ads(models.Model):
	"""
	首页广告
	"""
	name = models.CharField('广告主题',max_length=100)
	title = models.CharField('广告标题',null=True,blank=True,max_length=200)
	description = models.TextField('广告描述',null=True,blank=True)
	callback_url = models.URLField('回调url',blank=True)
	image_url = models.ImageField('图片路径',upload_to='ad/%Y/%m/%d',blank=True)
	date_publish = models.DateTimeField('添加日期',auto_now_add=True)
	play = models.BooleanField('是否显示',default=False)
	index = models.IntegerField('排列顺序（从小到大）',default=999)

	class Meta:
		verbose_name = '首页广告'
		verbose_name_plural = verbose_name
		ordering = ['index','id']

	def get_image_url(self):
		self.url = str(self.image_url)
		return os.path.join(settings.MEDIA_URL,self.url)

	def __str__(self):
		return self.name

class Brand(models.Model):
	"""
	商品品牌
	"""
	name = models.CharField('品牌名称',max_length=100)
	slug = models.SlugField('品牌标签',max_length=100)
	description = models.TextField('品牌描述')
	index = models.IntegerField('排列顺序（从小到大）',default=999)

	class Meta:
		verbose_name = '商品品牌'
		verbose_name_plural = verbose_name
		ordering = ['index','id']

	def __str__(self):
		return self.name

class Category(models.Model):
	"""
	商品分类名称
	"""
	name = models.CharField('分类名称',max_length=200,db_index=True)
	slug = models.SlugField('分类标签',max_length=200,db_index=True,unique=True)
	description = models.TextField('分类描述',blank=True)
	index = models.IntegerField('排列顺序（从小到大）',default=999)

	class Meta:
		verbose_name = '商品分类'
		verbose_name_plural = verbose_name
		ordering = ['index','id']

	def get_absolute_url(self):
		return reverse('shopsys:product_grid',args=[self.slug])

	def __str__(self):
		return self.name

class Product(models.Model):
	"""
	商品
	"""
	name = models.CharField('商品名称',max_length=200)
	slug = models.SlugField('商品标签',max_length=200)
	image_url = models.ImageField('图片路径',upload_to='product/%Y/%m/%d',blank=True)
	description = models.TextField('商品描述',blank=True)
	price = models.DecimalField('商品价格',max_digits=10,decimal_places=2)
	discount_price = models.DecimalField('打折价格',max_digits=10,decimal_places=2,blank=True)
	stock = models.PositiveIntegerField('商品货存')
	available = models.BooleanField('商品是否有效',default=True)
	created = models.DateTimeField('发布时间',auto_now_add=True)
	updated = models.DateTimeField('更新时间',auto_now=True)
	category = models.ForeignKey(Category,related_name='products',verbose_name='分类')
	brand = models.ManyToManyField(Brand,related_name='categorys',verbose_name='品牌')

	class Meta:
		verbose_name = '商品'
		verbose_name_plural = verbose_name
		ordering = ['name']
		index_together = ['id','slug']

	def get_absolute_url(self):
		return reverse('shopsys:product_detail',args=[self.id, self.slug])

	def get_image_url(self):
		self.url = str(self.image_url)
		return os.path.join(settings.MEDIA_URL,self.url)

	def __str__(self):
		return self.name

apps/orders/models.py
from django.db import models
from apps.catalog.models import *

# Create your models here.

class Order(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.EmailField()
	address = models.CharField(max_length=250)
	postal_code = models.CharField(max_length=20)
	city = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ['-created',]

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
	order = models.ForeignKey(Order,related_name='items')
	product = models.ForeignKey(Product,related_name='order_items')
	price = models.DecimalField(max_digits=10,decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def  get_cost(self):
		return self.price * self.quantity

apps/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(label="数量",choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
	# quantity = forms.IntegerField(label='数量',required=True,min_value=1,widget=forms.NumberInput(attrs={"class":"int_number","value":"1"}))
	update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

apps/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from apps.catalog.models import *
from apps.cart.forms import CartAddProductForm
from apps.cart import views
from apps.cart.cart import Cart


# Create your views here.

@require_POST
def cart_add(request,product_id):
	cart = Cart(request)
	product = get_object_or_404(Product,id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request,product_id):
	cart = Cart(request)
	product = get_object_or_404(Product,id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={"quantity":item['quantity'],'update':True})
	return render(request,'cart/shopping_cart.html',locals())

apps/catalog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.conf import settings
from apps.catalog.models import *
from apps.cart.forms import CartAddProductForm
from apps.cart.cart import Cart

# Create your views here.

def global_setting(request):
	site_manager = settings.SITE_MANAGER
	site_manager['logo'] = Logos.objects.get(pk=1)
	site_manager['ads'] = Ads.objects.filter(play=True)
	site_manager['categorys'] = Category.objects.all()[:6]
	site_manager['more_categorys'] = Category.objects.all()[6:]
	site_manager['muying'] = Category.objects.get(slug='baby')
	site_manager['baby'] = Product.objects.filter(category=site_manager['muying'])
	site_manager['cart'] = Cart(request)
	return site_manager


def index(request):
	return render(request,'web/index.html',locals())


def product_detail(request,id,slug):
	product = get_object_or_404(Product,id=id,slug=slug,available=True)
	cartaddproductform = CartAddProductForm()
	return render(request,'web/detail.html',locals())


def product_grid(request,category_slug=None):
	category = None
	grid = True
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	if grid:
		return render(request,'web/product_grid.html',locals())
	else:
		return render(request,'web/product_list.html',locals())

apps/orders/views.py
from django.shortcuts import render

# Create your views here.

templates/cart/shopping_cart.html
{% extends "web/base.html" %}
{% load staticfiles %}


{% block custom_css %}  
{% endblock %}



{% block custom_script %}
  <script src="{% static 'js/checkbox.js' %}"></script>
  <script src="{% static 'js/radio.js' %}"></script>
  <script src="{% static 'js/selectBox.js' %}"></script>
   <script>
       $(document).ready(function(){
        $("#myController").jFlow({
         controller: ".control", // must be class, use . sign
         slideWrapper : "#jFlowSlider", // must be id, use # sign
         slides: "#slider",  // the div where all your sliding divs are nested in
         selectedWrapper: "jFlowSelected",  // just pure text, no sign
         width: "984px",  // this is the width for the content-slider
         height: "480px",  // this is the height for the content-slider
         duration: 400,  // time in miliseconds to transition one slide
         prev: ".slidprev", // must be class, use . sign
         next: ".slidnext", // must be class, use . sign
         auto: true
        });
       });
  </script>
  <script>
       $(function() {
    $('#list_product').carouFredSel({
    prev: '#prev_c1',
    next: '#next_c1',
    auto: false
    });
          $('#list_product2').carouFredSel({
    prev: '#prev_c2',
    next: '#next_c2',
    auto: false
    });
    $(window).resize();
  });
  </script>
  <script>
       $(document).ready(function(){
        $("button").click(function(){
         $(this).addClass('click')
        });
       })
  </script>
  <script>
       $(document).ready(function() {
        $("select").selectBox();
       });
  </script>

{% endblock %}


{% block body %}

  <section id="main" class="entire_width">
    <div class="container_12">
       <div class="grid_12">
       <h1 class="page_title">购物车</h1>

       <table class="cart_product">
        <tr>
         <th class="images"></th>
         <th class="bg name">商品名称</th>
         <th class="edit"> </th>
         <th class="bg price">单价</th>
         <th class="qty">数量</th>
         <th class="bg subtotal">共计</th>
         <th class="close"> </th>
        </tr>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
         <td class="images"><a href="{{ product.get_absolute_url }}"><img src="{{ product.get_image_url }}" alt="Product 6"></a></td>
         <td class="bg name">{{ product.name }}<br/> Jasmine, 4-Ounces</td>
         <td class="edit"><a title="Edit" href="#">Edit</a></td>
         <td class="bg price">¥{{ item.price }}</td>
         <!-- <td class="qty"><input type="text" name="" value="" placeholder="{{ item.quantity }}" /></td> -->
         <td>
         <form action="{% url 'cart:cart_add' product.id %}" method="post">
         {% csrf_token %}
         {{ item.update_quantity_form.quantity }}
         {{ item.update_quantity_form.update }}
         <input type="submit" value="Update">
         </form>
         </td>
         <td class="bg subtotal">¥{{ item.total_price }}</td>
         <td class="close"><a title="close" class="close" href="{% url 'cart:cart_remove' product.id %}"></a></td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr>
         <td colspan="7" class="cart_but">
          <button class="continue"><span>icon</span>返回继续购物</button>
          <button class="update"><span>icon</span>更新购物清单</button>
         </td>
        </tr>
       </table>
       </div><!-- .grid_12 -->

       <div id="content_bottom">
        <div class="grid_4">
          <div class="bottom_block estimate">
            <h3>Estimate Shipping and Tax</h3>
            <p>Enter your destination to get a shipping estimate.</p>
      <form>
        <p>
         <strong>Country:</strong><sup class="surely">*</sup><br/>
         <select>
          <option>United States</option>
          <option>United States</option>
         </select>
        </p>
        <p>
         <strong>State/Province:</strong><br/>
         <select>
          <option>Please select region, state or province</option>
          <option>Please select region, state or province</option>
         </select>
        </p>
        <p>
         <strong>Zip/Postal Code</strong><br/>
         <input type="text" name="" value="" />
        </p>
        <input type="submit" id="get_estimate" value="Get a Quote" />
      </form>

          </div><!-- .estimate -->
        </div><!-- .grid_4 -->

        <div class="grid_4">
          <div class="bottom_block discount">
            <h3>Discount Codes</h3>
            <p>Enter your coupon code if you have one.</p>
      <form>
        <p>
         <input type="text" name="" value="" placeholder="United States"/>
        </p>
        <input type="submit" id="apply_coupon" value="Apply Coupon" />
      </form>
          </div><!-- .discount -->
        </div><!-- .grid_4 -->

        <div class="grid_4">
          <div class="bottom_block total">
        <table class="subtotal">
         <tr>
          <td>Subtotal</td><td class="price">$1, 500.00</td>
         </tr>
         <tr class="grand_total">
          <td>Grand Total</td><td class="price">$1, 500.00</td>
         </tr>
        </table>
      <button class="checkout">PROCEED TO CHECKOUT</button>
            <a href="#">Checkout with Multiple Addresses</a>
          </div><!-- .total -->
        </div><!-- .grid_4 -->

        <div class="clear"></div>
      </div><!-- #content_bottom -->
      <div class="clear"></div>

      <div class="clear"></div>

      <div class="carousel" id="following">
        <div class="c_header">
          <div class="grid_10">
            <h5>Based on your selection, you may be interested in the following item:</h5>
          </div><!-- .grid_10 -->

          <div class="grid_2">
            <a id="next_c1" class="next arows" href="#"><span>Next</span></a>
            <a id="prev_c1" class="prev arows" href="#"><span>Prev</span></a>
           </div><!-- .grid_2 -->
        </div><!-- .c_header -->

        <div class="list_carousel">

        <ul id="list_product" class="list_product">
          <li class="">
            <div class="grid_3 product">
              <img class="sale" src="images/sale.png" alt="Sale"/>
              <div class="prev">
                <a href="product_page.html"><img src="images/product_1.png" alt="" title="" /></a>
              </div><!-- .prev -->
              <h3 class="title">Febreze Air Effects New Zealand Springs</h3>
              <div class="cart">
                <div class="price">
                <div class="vert">
                  <div class="price_new">$550.00</div>
                  <div class="price_old">$725.00</div>
                </div>
                </div>
                <a href="#" class="obn"></a>
                <a href="#" class="like"></a>
                <a href="#" class="bay"></a>
              </div><!-- .cart -->
            </div><!-- .grid_3 -->
          </li>

          <li class="">
            <div class="grid_3 product">
              <img class="sale" src="images/sale.png" alt="Sale"/>
              <div class="prev">
                <a href="product_page.html"><img src="images/product_2.png" alt="" title="" /></a>
              </div><!-- .prev -->
              <h3 class="title">Febreze Air Effects New Zealand Springs</h3>
              <div class="cart">
                <div class="price">
                <div class="vert">
                  <div class="price_new">$550.00</div>
                  <div class="price_old">$725.00</div>
                </div>
                </div>
                <a href="#" class="obn"></a>
                <a href="#" class="like"></a>
                <a href="#" class="bay"></a>
              </div><!-- .cart -->
            </div><!-- .grid_3 -->
          </li>

          <li class="">
            <div class="grid_3 product">
              <div class="prev">
                <a href="product_page.html"><img src="images/product_3.png" alt="" title="" /></a>
              </div><!-- .prev -->
              <h3 class="title">Febreze Air Effects New Zealand Springs</h3>
              <div class="cart">
                <div class="price">
                <div class="vert">
                  <div class="price_new">$550.00</div>
                </div>
                </div>
                <a href="#" class="obn"></a>
                <a href="#" class="like"></a>
                <a href="#" class="bay"></a>
              </div><!-- .cart -->
            </div><!-- .grid_3 -->
          </li>

          <li class="">
            <div class="grid_3 product">
              <img class="sale" src="images/sale.png" alt="Sale"/>
              <div class="prev">
                <a href="product_page.html"><img src="images/product_4.png" alt="" title="" /></a>
              </div><!-- .prev -->
              <h3 class="title">Febreze Air Effects New Zealand Springs</h3>
              <div class="cart">
                <div class="price">
                <div class="vert">
                  <div class="price_new">$550.00</div>
                  <div class="price_old">$725.00</div>
                </div>
                </div>
                <a href="#" class="obn"></a>
                <a href="#" class="like"></a>
                <a href="#" class="bay"></a>
              </div><!-- .cart -->
            </div><!-- .grid_3 -->
          </li>

          <li class="">
            <div class="grid_3 product">
              <div class="prev">
                <a href="product_page.html"><img src="images/product_5.png" alt="" title="" /></a>
              </div><!-- .prev -->
              <h3 class="title">Febreze Air Effects New Zealand Springs</h3>
              <div class="cart">
                <div class="price">
                <div class="vert">
                  <div class="price_new">$550.00</div>
                  <div class="price_old">$725.00</div>
                </div>
                </div>
                <a href="#" class="obn"></a>
                <a href="#" class="like"></a>
                <a href="#" class="bay"></a>
              </div><!-- .cart -->
            </div><!-- .grid_3 -->
          </li>

        </ul><!-- #list_product -->
        </div><!-- .list_carousel -->
      </div><!-- .carousel -->

    </div><!-- .container_12 -->
  </section><!-- #main -->
{% endblock %}

templates/web/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<head>
  <meta charset="UTF-8">
  <meta name="description" content="">
  <meta name="keywords" content="">

  <title>{% block title %}{{ SITE_NAME }}{% endblock %}</title>

  <link rel="shortcut icon" href="favicon.ico">
  <link href="{% static 'css/style.css' %}" media="screen" rel="stylesheet" type="text/css">
  <link href="{% static 'css/grid.css' %}" media="screen" rel="stylesheet" type="text/css">


  {% block custom_css %}{% endblock %}
  

  <script src="{% static 'js/jquery-1.7.2.min.js' %}" ></script>
  <script src="{% static 'js/html5.js' %}" ></script>
  <script src="{% static 'js/jflow.plus.js' %}" ></script>
  <script src="{% static 'js/jquery.carouFredSel-5.2.2-packed.js' %}"></script>

  {% block custom_script %}{% endblock %}


  <script>
	$(document).ready(function(){
	    $("#myController").jFlow({
			controller: ".control", // must be class, use . sign
			slideWrapper : "#jFlowSlider", // must be id, use # sign
			slides: "#slider",  // the div where all your sliding divs are nested in
			selectedWrapper: "jFlowSelected",  // just pure text, no sign
			width: "984px",  // this is the width for the content-slider
			height: "480px",  // this is the height for the content-slider
			duration: 400,  // time in miliseconds to transition one slide
			prev: ".slidprev", // must be class, use . sign
			next: ".slidnext", // must be class, use . sign
			auto: true
    });
  });
  </script>
  <script>
	$(function() {
	  $('#list_product').carouFredSel({
		prev: '#prev_c1',
		next: '#next_c1',
		auto: false
	  });
      $('#list_product2').carouFredSel({
		prev: '#prev_c2',
		next: '#next_c2',
		auto: false
	  });
	  $('#list_product3').carouFredSel({
		prev: '#prev_c3',
		next: '#next_c3',
		auto: false
	  });
	  $('#list_product4').carouFredSel({
		prev: '#prev_c4',
		next: '#next_c4',
		auto: false
	  });
	  $('#list_product5').carouFredSel({
		prev: '#prev_c5',
		next: '#next_c5',
		auto: false
	  });
	  $('#list_product6').carouFredSel({
		prev: '#prev_c6',
		next: '#next_c6',
		auto: false
	  });
	  $(window).resize();
	});
  </script>
  <script>
       $(document).ready(function(){
	      $("button").click(function(){
		     $(this).addClass('click')
	      });
       })
  </script>

</head>
<body>
  <div class="container_12">
    <div id="top">
      <div class="grid_3">
        <div class="phone_top">
          Call IPhone 13719433887
        </div><!-- .phone_top -->
      </div><!-- .grid_3 -->

      <div class="grid_6">
        <div class="welcome">
          欢迎浏览本店
        </div><!-- .welcome -->
      </div><!-- .grid_6 -->
      <div class="grid_3">
<!--         <div class="valuta">
          <ul>
            <li class="curent"><a href="#">$</a></li>
            <li><a href="#">&#8364;</a></li>
            <li><a href="#">&#163;</a></li>
          </ul>
        </div> --><!-- .valuta -->

<!--         <div class="lang">
          <ul>
            <li class="curent"><a href="#">EN</a></li>
            <li><a href="#">FR</a></li>
            <li><a href="#">GM</a></li>
          </ul>
        </div> --><!-- .lang -->
      </div><!-- .grid_3 -->
    </div><!-- #top -->

    <div class="clear"></div>

    <header id="branding">
      <div class="grid_3">
        <hgroup>
          <h1 id="site_logo" ><a href="{% url 'shopsys:index' %}" title=""><img src="{{ MEDIA_URL }}{{ logo.image_url }}" alt="Online Store Theme Logo"/></a></h1>
          <h2 id="site_description">{{ logo.description }}</h2>
        </hgroup>
      </div><!-- .grid_3 -->

      <div class="grid_3">
        <form class="search">
          <input type="text" name="search" class="entry_form" value="" placeholder="Search entire store here..."/>
	</form>
      </div><!-- .grid_3 -->

      <div class="grid_6">
        <ul id="cart_nav">
          <li>
            <a class="cart_li" href="{% url 'cart:cart_detail' %}">我的购物袋</a>
            <ul class="cart_cont">
              <li class="no_border"><p><h4>购物清单</h4></p></li>
              {% if cart|length > 0 %}
              {% for item in cart %}
              {% with product=item.product %}
              <li>
                <a href="{{ product.get_absolute_url }}" class="prev_cart"><div class="cart_vert"><img src="{{ product.get_image_url }}" alt="" title="" /></div></a>
                <div class="cont_cart">
                  <h4>{{ product.name }}</h4>
                  <div class="price">{{ item.quantity }} x ¥{{ item.total_price }}</div>
                </div>
                <!-- <a title="close" class="close" href="{% url 'cart:cart_remove' product.id %}"></a> -->
                <div class="clear"></div>
              </li>
              {% endwith %}
              {% endfor %}
              {% else %}
              <li>
                <div class="cont_cart">
                  <h4>您的购物袋还没有商品，去逛逛吧~</h4>
                </div>
                <div class="clear"></div>
              </li>
              {% endif %}
    	      <li class="no_border">
          		<a href="" class="view_cart">清空购物车</a>
          		<a href="{% url 'cart:cart_detail' %}" class="checkout">去购物车结算</a>
    	      </li>
            </ul>
          </li>
        </ul>

        <nav class="private">
          <ul>
            <li><a href="#">我的信息</a></li>
		<li class="separator">|</li>
            <li><a href="#">我的订单</a></li>
		<li class="separator">|</li>
            <li><a href="login.html">登录</a></li>
		<li class="separator">|</li>
            <li><a href="login.html">退出</a></li>
          </ul>
        </nav><!-- .private -->
      </div><!-- .grid_6 -->
    </header><!-- #branding -->
  </div><!-- .container_12 -->

  <div class="clear"></div>

  <div id="block_nav_primary">
    <div class="container_12">
      <div class="grid_12">
        <nav class="primary">
          <ul>
            <li class="curent"><a href="{% url 'shopsys:index' %}">首页</a></li>
            {% for category in categorys %}
                <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                </li>
            {% endfor %}
            <li><a href="">更多</a>
              <ul class="sub">
              {% for category in more_categorys %}
                <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
              {% endfor %}  
              </ul>
            </li>
          </ul>
        </nav><!-- .primary -->
      </div><!-- .grid_12 -->
    </div><!-- .container_12 -->
  </div><!-- .block_nav_primary -->

  <div class="clear"></div>

{% block body %}
{% block ad %}
{% endblock ad %}
{% endblock body %}

  <div class="clear"></div>

{% block footer %}
  <footer>
    <div class="f_navigation">
      <div class="container_12">
        <div class="grid_3">
          <h3>联系方式</h3>
          <ul class="f_contact">
            <li>广东省广州市</li>
            <li>020-xxxx-xxxx</li>
            <li>linky_sky@163.com</li>
          </ul><!-- .f_contact -->
        </div><!-- .grid_3 -->

        <div class="grid_3">
          <h3>服务保障</h3>
          <nav class="f_menu">
            <ul>
              <li><a href="#">正品保证</a></li>
              <li><a href="#">7天无理由放心退</a></li>
              <li><a href="#">退货返运费</a></li>
              <li><a href="#">7x15小时客户服务</a></li>
            </ul>
          </nav><!-- .private -->
        </div><!-- .grid_3 -->


        <div class="grid_3">
          <h3>支付方式</h3>
          <nav class="f_menu">
            <ul>
              <li><a href="contact_us.html">快捷支付</a></li>
              <li><a href="#">23家主流网银支付</a></li>
              <li><a href="#">货到付款</a></li>
              <li><a href="#">支付宝、银联等支付</a></li>
              <li><a href="#">信用卡支付</a></li>
            </ul>
          </nav><!-- .private -->
        </div><!-- .grid_3 -->

        <div class="grid_3">
          <h3>售后服务</h3>
          <nav class="f_menu">
            <ul>
              <li><a href="#">退货政策</a></li>
              <li><a href="#">退货流程</a></li>
              <li><a href="#">退款方式和时效</a></li>
            </ul>
          </nav><!-- .private -->
        </div><!-- .grid_3 -->

        <div class="clear"></div>
      </div><!-- .container_12 -->
    </div><!-- .f_navigation -->

    <div class="f_info">
      <div class="container_12">
        <div class="grid_6">
          <p class="copyright">Copyright © 2008-2016，All Rights Reserved，粤ICP备00000000号，版权所有、</p>
        </div><!-- .grid_6 -->

        <div class="grid_6">
          <div class="soc">
            <a class="google" href=""></a>
            <a class="twitter" href=""></a>
            <a class="facebook" href=""></a>
          </div><!-- .soc -->
        </div><!-- .grid_6 -->

        <div class="clear"></div>
      </div><!-- .container_12 -->
    </div><!-- .f_info -->
  </footer>
{% endblock footer %}

</body>
</html>